workflows:
  testFlight:
    name: "Stillscreen: Focus Launcher"

    integrations:
      app_store_connect: SpeedTeste

    environment:
      flutter: stable

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.zyverio.focuslauncher

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Set up iOS code signing
        script: xcode-project use-profiles

      - name: Build IPA
        script: |
          flutter build ipa \
            --release \
            --build-number="$BUILD_NUMBER" \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      email:
        recipients:
          - hornet.devlo@gmail.com
        notify:
          success: true
          failure: true

      app_store_connect:
        auth: integration
